services:
  - type: web
    name: sidelines
    env: docker
    plan: free
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
